apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
type: Opaque
stringData:
  DATABASE_NAME: {{ .Values.service.db.dbname }}
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.service.db.host .Values.service.db.sport .Values.service.db.dbname }}
  DATABASE_SCHEMA: {{ .Values.service.db.dbschema }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.service.db.username }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.service.db.password }}
