version: '3.9'

services:
  warehouse-db:
    image: postgres:16-alpine
    container_name: warehouse-postgres
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - warehouse-data:/var/lib/postgresql/data

  warehouse-app:
    image: warehouse-app:latest
    container_name: warehouse-app
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - warehouse-db


  kafka:
    image: confluentinc/cp-kafka:7.9.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: 6345ABF7-73E9-4465-A61D-8411DA125CF3
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-0.kafka-kraft-kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka-0.kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./kafka.properties:/etc/kafka/kafka.properties
    command:
      - sh
      - -c
      - |
        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          echo "⏳ Initializing Kafka cluster..."
          /usr/bin/kafka-storage format --ignore-formatted --cluster-id 6345ABF7-73E9-4465-A61D-8411DA125CF3 --config /etc/kafka/kafka.properties
        fi
        /etc/confluent/docker/run

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

volumes:
  warehouse-data:
  kafka-data: