#inter.broker.listener.name=PLAINTEXT
#process.roles=broker,controller
#controller.listener.names=CONTROLLER
#controller.quorum.voters=0@kafka-0.kafka-kraft-kafka:29092
#auto.create.topics.enable=true
#node.id=0
#advertised.listeners=PLAINTEXT://kafka-kraft-kafka.default.svc.cluster.local:9092
#listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
#listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29092
#zookeeper.connect=
#log.dirs=/var/lib/kafka/data
