inter.broker.listener.name=PLAINTEXT
process.roles=broker,controller
controller.listener.names=CONTROLLER
controller.quorum.voters=1@kafka-0.kafka-kraft-kafka:9093
auto.create.topics.enable=true
node.id=1
advertised.listeners=PLAINTEXT://kafka:9092
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
listeners=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
zookeeper.connect=
log.dirs=/var/lib/kafka/data
