{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:

        paths:
          - path: /(.*) #запросы по такому адресу в кластер будут направляться в сервис demo-service на порт 8088
            pathType: Prefix
            backend:
              service:
                name: {{ include "chart.fullname" $ }}
                port:
                  number: 8088 #должно соответствовать порту сервиса, который в свою очередь указывает на 9090 порт пода

          - path: /(actuator(?:/|$).*) #запросы по такому адресу в кластер будут направляться в сервис demo-service на порт 9099
            pathType: Prefix
            backend:
              service:
                name: {{ include "chart.fullname" $ }}
                port:
                  number: 9099 #должно соответствовать порту сервиса, который в свою очередь указывает на 9090 порт пода
{{/*        paths:*/}}
{{/*          {{- range .Values.ingress.paths }}*/}}
{{/*          - path: {{ .path }}*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ include "chart.fullname" $ }}*/}}
{{/*                port:*/}}
{{/*                  number: {{ .port }}*/}}
{{/*          {{- end }}*/}}
{{- end }}