spring.application.name=warehouse

# URL ??????????? ? ????
spring.datasource.url=jdbc:postgresql://localhost:5432/warehouse_db

# ????? ? ?????? ??? PostgreSQL ???? ??????
spring.datasource.username=postgres
spring.datasource.password=postgres


# ????????? JPA ? Hibernate:

# ????????????? ????????? ????????? ?????? ? ????, ???????? ?????????? ? ????????? (?????? ?? ????? ??????????).
spring.jpa.hibernate.ddl-auto=update

# ??? ???????? ??????? SQL-??????? ? ??????? ??? ??????? ? ????????????? ??????????.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true