spring.application.name=warehouse

# URL database connection
spring.datasource.url=${SPRING_DATASOURCE_URL}

# PostgreSQL database login and password
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# JPA and Hibernate props:

# Autoupdate database tables, if changing models.
# spring.jpa.hibernate.ddl-auto=update
# or custom migrate tables
spring.jpa.hibernate.ddl-auto=validate

# logging SQL-requests.
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# liquibase properties
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# scheduling properties
app.scheduling.enabled=true
scheduling.optimization=true
scheduling.price-change.simple.cron=0 * * * * ?
scheduling.price-change.simple.percent=-0.01f
scheduling.price-change.optimized.cron=0 * * * * ?
scheduling.price-change.optimized.percent=0.01f

# aspects enable property
spring.aop.auto=true
