
management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, beans, mappings

spring:
  config:
    activate:
      on-profile: default
  application:
    name: warehouse

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  aop:
    auto: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://rhumb.mediasoft.team/rhumb-auth-api/auth/.well-known/jwks.json

  cache:
    cache-names: currencies
    type: caffeine
    caffeine:
      spec: expireAfterWrite=60s

  kafka:
    listener:
      ack-mode: manual
    bootstrap-servers:
      - ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: test-consumer-group-1
      auto-offset-reset: earliest

s3:
  endpoint: ${S3_ENDPOINT}
  region: us-east-1
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
  bucket: product-images
app:
  scheduling:
    enabled: false

scheduling:
  optimization: false
  price-change:
    simple:
      cron: "0 * * * * ?"
      percent: -0.01f
      batch-size: 100000
      export-file-path: export/products_simple.csv
    optimized:
      cron: "0 * * * * ?"
      percent: 0.01f
      batch-size: 100000
      export-file-path: export/products.csv
    entity-manager:
      enabled: false
      cron: "0 * * * * ?"
      percent: 0.01f
      batch-size: 100000
      export-file-path: export/products.csv

rest:
  inn:
    mock-enabled: false
    host: ${INN_SERVICE_HOST:http://inn-service}
    methods:
      inns: /api/inns
  account-number:
    mock-enabled: false
    host: ${ACCOUNT_NUMBER_SERVICE_HOST:http://account-number-service}
    methods:
      accountNumbers: /api/account-numbers
  currency:
    mock-enabled: false
    host:  ${CURRENCY_SERVICE_HOST:http://currency-service}
    methods:
      currencies: /api/currencies
#logging:
#  level:
#    org.springframework.kafka.listener: DEBUG
---

spring:
  config:
    activate:
      on-profile: test
  application:
    name: warehouse

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
