spring.application.name=warehouse-local

# H2 ????????????
spring.datasource.url=jdbc:h2:mem:warehouse_db;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.settings.web-allow-others=true

# Liquibase ??? H2
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# ????????? Hibernate ??? ???????? ????????????
spring.jpa.hibernate.ddl-auto=create

# ???????? ???-??????? H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# logging SQL-requests.
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# scheduling properties
app.scheduling.enabled=false