spring.application.name=warehouse

# URL database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/warehouse_db

# PostgreSQL database login and password
spring.datasource.username=postgres
spring.datasource.password=postgres


# JPA and Hibernate props:

# Autoupdate database tables, if changing models.
# or custom migrate tables
# spring.jpa.hibernate.ddl-auto=update

# logging SQL-requests.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true