apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "external-service.fullname" . }}
  labels:
    app: {{ include "external-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "external-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "external-service.name" . }}
    spec:
      containers:
        - name: external-contract-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
