apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:

  kafka.properties: |
    # пример конфигурации
    process.roles=broker,controller
    node.id=1
    controller.quorum.voters=1@kafka-0.kafka-kraft-kafka:9093
    listeners=PLAINTEXT://:9092,CONTROLLER://:9093
    advertised.listeners=PLAINTEXT://{{ .Release.Name }}-kafka:9092
    controller.listener.names=CONTROLLER
    log.dirs={{ .Values.kafka.logDir }}
    num.network.threads=3
    num.io.threads=8
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    num.partitions=1
    default.replication.factor=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    group.initial.rebalance.delay.ms=0