#apiVersion: v2
#name: warehouse-app
#version: 1.0.0
#description: WarehouseApp
#type: application
#maintainers:
#  - name: Vassiliy Somov
#    email: vassuv@ya.ru
#appVersion: 1.0.0
#keywords:
#  - warehouse
#  - backend
#  - springboot
#sources:
#  - https://github.com/VASSUV/TestMediasoftTask