namespace: warehouse-ns
appName: warehouse

replicaCount: 2

secret:
  name: warehouse-secret
deployment:
  db:
    image: postgres:latest
    port: 5432
    replicas: 1

image:
  repository: warehouse-app
  tag: v32
  pullPolicy: IfNotPresent

config:
  innServiceHost: http://inn-inn-service.inn-ns.svc.cluster.local:8083
  accountNumberServiceHost: http://account-number-account-number-service.account-number-ns.svc.cluster.local:8084
  currencyServiceHost: http://currency-currency-service.currency-ns.svc.cluster.local:8082
  kafkaServiceHost: kafka-kraft-kafka.default.svc.cluster.local:9092

service:
  type: LoadBalancer
  db:
    name: postgresql-warehouse-postgres-service
    host: "postgresql-warehouse-postgres-service"
    type: ClusterIP
    port: 5432
    sport: "5432"
    dbname: warehouse_db
    dbschema: public
    username: admin # YWRtaW4= #admin
    password: password # cGFzc3dvcmQ= #password

ingress:
  enabled: true
  className: nginx
  host: minikube
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1


nodeSelector: {}

tolerations: []

affinity: {}

